Add AI Tools directory and WormGPT-6
lockfale/OSINT-Framework pull request #388
Opened 2024-06-12 07:25 UTC by Akshit-Chilkoti

I have made a new directory 'AI Tools'. I have also added WormGPT-6 AI to this catagory. Unlike ChatGPT, WormGPT does not invoke ethical standards, legal considerations. This allows it to provide answers that can not be provided by ChatGPT.

2024-06-15 16:30 UTC, Xraypower approved these changes

2024-06-15 17:46 UTC, Invisibleman9 approved these changes

2024-06-15 17:49 UTC, Invisibleman9 commented
Thanks

2024-06-15 18:29 UTC, Invisibleman9 approved these changes

2024-06-15 18:29 UTC, Invisibleman9 requested changes
Thanks

2024-06-15 18:35 UTC, Invisibleman9 approved these changes

2024-06-15 21:14 UTC, Invisibleman9 approved these changes

2024-07-02 03:49 UTC, merged

2024-07-10 01:39 UTC, Invisibleman9 reviewed
Thanks

2025-07-24 05:46 UTC, seif1611 approved these changes